server:
  host: 127.0.0.1
  port: 8080

database:
  url: "sqlite:///db.sqlite3"

backup:
  dir: var/backup
  interval: 3600
  count: 20

logging:
  dir: var/log
  filename: "configfactory.log"

environments:
  - alias: development
    name: Development
  - alias: migration
    name: Migration
    fallback: development
  - alias: production
    name: Production

users:
  - username: admin
    password: admin
    is_admin: true
  - username: guest
    password: guest
    is_admin: false
    permissions:
      - "environment:base:read"
      - "environment:base:write"
      - "environment:development:read"
      - "environment:development:write"
      - "environment:migration:write"
      - "environment:production:read"
